@startuml ActivityData
title Activity Data
skinparam Linetype ortho

package Luxon {
  class DateTime <<external>>
  class Interval <<external>>

  Interval o-left-> "2" DateTime
}

enum ActivityType {
  UNKNOWN
  ==
  SITUPS
  SQUATS
  PUSHUPS
  STAR_JUMPS
}

interface ActivityTracking{
  meta: ActivityTrackingMeta
  accelerometer: SensorAsyncSample[]
  gyroscope: SensorAsyncSample[]
  magnetometer: SensorAsyncSample[]
}

interface ActivityTrackingMeta{
  type: ActivityType
  interval: Interval
  repeats: number
}


interface SensorAsyncSample {
  timestamp: DateTime
  data: AxesData
}

interface AxesData {
  x: number
  y: number
  z: number
}

interface SensorForcedSample {
  altitude?: number
  pressure?: number
  temperature?: number
  illuminance?: number
}

ActivityTrackingMeta --> ActivityType
SensorAsyncSample *--> DateTime
ActivityTrackingMeta *--> Interval
ActivityTracking "1..*" *-->  SensorAsyncSample
ActivityTracking "1" *-->  ActivityTrackingMeta

SensorAsyncSample *--> AxesData
@enduml
