@startuml ActivityData
title Activity Data
skinparam Linetype ortho

package Luxon {
  class DateTime <<external>>
  class Interval <<external>>

  Interval o-left-> "2" DateTime
}

enum ActivityType {
  UNKNOWN
  ==
  SITUPS
  SQUATS
  PUSHUPS
  STAR_JUMPS
}

interface ActivityTrackingDTO{
  meta: ActivityTrackingMeta
  interval: Interval
  data: SensorBasicSample[]
}

interface ActivityTrackingMeta{
  type: ActivityType
  timestamp: DateTime
  repeats: number
}


interface SensorBasicSample {
  acceleration: [number, number, number]
  angularVelocity: [number, number, number]
  magneticField: [number, number, number]
}

interface SensorExtendedSample extends SensorBasicSample {
  altitude?: number
  pressure?: number
  illuminance?: number
}

ActivityTrackingMeta --> ActivityType
ActivityTrackingDTO -> Interval
ActivityTrackingDTO  *--> "1..*" SensorBasicSample
ActivityTrackingDTO  *-->  ActivityTrackingMeta

@enduml
