version: '3.9'
services:
  ml_bridge:
    build:
      dockerfile: ./apps/ml-bridge/Dockerfile
      context: ../../
    expose:
      - "3333"
    volumes:
      - .:/code/apps/ml-bridge
    environment:
      ML_BASE_URL: http://ml_api:8000/api/v1/classify_data
    deploy:
      replicas: 4

  nginx:
    build:
      dockerfile: ./config/Dockerfile
      context: ./
    depends_on:
      - ml_bridge
    ports:
      - "4000:4000"

networks:
  default:
    driver: bridge
    name: ml_bridge