version: '3.9'
services:
  core_api:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./app/:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload
    restart: unless-stopped
